# Doc2Vec Configuration
sources:
  - type: local_directory
    product_name: 'solo-reference-architectures'
    version: 'latest'
    path: './solo-reference-architectures'
    include_extensions: ['.md']
    exclude_extensions: []
    recursive: true
    url_rewrite_prefix: https://github.com/solo-io/solo-reference-architectures/blob/main
    max_size: 1048576
    database_config:
      type: 'qdrant'
      params:
        qdrant_url: 'https://qdrant.is.solo.io'
        qdrant_port: 443
        collection_name: 'github-solo-reference-architectures-tmp'
  # GitHub Sources
  - type: github
    product_name: 'istio'
    version: 'latest'
    repo: 'istio/istio'
    start_date: '2025-01-01'
    max_size: 1048576
    database_config:
      type: 'sqlite'
      params:
        db_path: './istio-issues.db'

  # Website Sources
  - type: website
    product_name: 'ambient'
    version: 'latest'
    url: 'https://ambientmesh.io/docs/'
    max_size: 1048576
    database_config:
      type: 'sqlite'
      params:
        db_path: './ambient.db'

  - type: website
    product_name: 'argo'
    version: 'latest'
    url: 'https://argo-cd.readthedocs.io/en/stable/'
    max_size: 1048576
    database_config:
      type: 'sqlite'
      params:
        db_path: './argo.db'

  - type: website
    product_name: 'argo-rollouts'
    version: 'latest'
    url: 'https://argoproj.github.io/argo-rollouts/installation/'
    max_size: 1048576
    database_config:
      type: 'sqlite'
      params:
        db_path: './argo-rollouts.db'

  - type: website
    product_name: 'argo-rollouts'
    version: 'latest'
    url: 'https://rollouts-plugin-trafficrouter-gatewayapi.readthedocs.io/en/latest/'
    max_size: 1048576
    database_config:
      type: 'sqlite'
      params:
        db_path: './argo-rollouts.db'

  - type: website
    product_name: 'cilium'
    version: 'latest'
    url: 'https://docs.cilium.io/en/stable/'
    max_size: 1048576
    database_config:
      type: 'sqlite'
      params:
        db_path: './cilium.db'

  - type: website
    product_name: 'gateway-api'
    version: 'latest'
    url: 'https://gateway-api.sigs.k8s.io/'
    max_size: 1048576
    database_config:
      type: 'sqlite'
      params:
        db_path: './gateway-api.db'

  - type: website
    product_name: 'gloo-mesh-core'
    version: 'latest'
    url: 'https://docs.solo.io/gloo-mesh/latest/'
    sitemap_url: 'https://docs.solo.io/gloo-mesh/sitemap.xml'
    max_size: 1048576
    database_config:
      type: 'sqlite'
      params:
        db_path: './gloo-mesh-core.db'

  - type: website
    product_name: 'gloo-mesh-enterprise'
    version: 'latest'
    url: 'https://docs.solo.io/gloo-mesh-enterprise/latest/'
    sitemap_url: 'https://docs.solo.io/gloo-mesh-enterprise/sitemap.xml'
    max_size: 1048576
    database_config:
      type: 'sqlite'
      params:
        db_path: './gloo-mesh-enterprise.db'

  - type: website
    product_name: 'gloo-edge'
    version: 'latest'
    url: 'https://docs.solo.io/gloo-edge/latest/'
    max_size: 1048576
    database_config:
      type: 'sqlite'
      params:
        db_path: './gloo-edge.db'

  - type: website
    product_name: 'gloo-gateway'
    version: 'latest'
    url: 'https://docs.solo.io/gateway/latest/'
    sitemap_url: 'https://docs.solo.io/gateway/sitemap.xml'
    max_size: 1048576
    database_config:
      type: 'sqlite'
      params:
        db_path: './gloo-gateway.db'

  - type: website
    product_name: 'helm'
    version: 'latest'
    url: 'https://helm.sh/docs/'
    max_size: 1048576
    database_config:
      type: 'sqlite'
      params:
        db_path: './helm.db'

  - type: website
    product_name: 'istio'
    version: 'latest'
    url: 'https://istio.io/latest/docs/'
    max_size: 1048576
    database_config:
      type: 'sqlite'
      params:
        db_path: './istio.db'

  - type: website
    product_name: 'kubernetes'
    version: 'latest'
    url: 'https://kubernetes.io/docs/'
    max_size: 1048576
    database_config:
      type: 'sqlite'
      params:
        db_path: './kubernetes.db'

  - type: website
    product_name: 'otel'
    version: 'latest'
    url: 'https://opentelemetry.io/docs/'
    max_size: 1048576
    database_config:
      type: 'sqlite'
      params:
        db_path: './otel.db'

  - type: website
    product_name: 'prometheus'
    version: 'latest'
    url: 'https://prometheus.io/docs/'
    max_size: 1048576
    database_config:
      type: 'sqlite'
      params:
        db_path: './prometheus.db'